# Generated by Django 3.2 on 2021-06-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('data_assunzione', models.DateField()),
                ('specialita', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Medici',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('indirizzo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('medico', models.ManyToManyField(to='studio.Medico')),
            ],
            options={
                'verbose_name_plural': 'Studi',
            },
        ),
    ]
